name: verifyip2location
description: Verifies the source of ip connections and domains from IP2Location and Whois ip2location.io.
version: 1.0.1-dev.1
repository: https://github.com/Hegeldirkk/verifyip2location.git

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:


environment:
  sdk: ^3.1.0-213.0.dev

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
